
on:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  push:
    branches:
      - main

jobs:
  noties:
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.notable.indepth.svg
        token: ${{ secrets.USER_TOKEN }}
        base: ""
        plugin_notable: yes
        plugin_notable_indepth: yes
        plugin_notable_repositories: yes
        plugin_notable_skipped: ${{ secrets.IGNORE_REPO }}
