on:
  schedule:
    - cron: '0 */4 * * *' # every 12 hours
  push:
    branches:
      - master
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: update svg    
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.notable.indepth.svg
        token: ${{ secrets.USER_TOKEN }}
        base: ""
        plugin_notable: yes
        plugin_notable_indepth: yes
        plugin_notable_repositories: yes
        plugin_notable_skipped: ${{ secrets.IGNORE_REPO }}    
    - name: gen readme
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.USER_TOKEN }}
    - name: push
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "."
          git push --force
        fi
